import {products, variants, pageNames, improvements, improvementsEn} from './data.js';
const $=s=>document.querySelector(s);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const byId=id=>products.find(p=>p.id===id);
let state, selected='papuga', filter='all', query='';
const t=(uk,en)=>state.lang==='uk'?uk:en;
const txt=x=>x[state.lang];
const name=p=>txt(p.name);
function url(page=state.page,extra={}){return `?${new URLSearchParams({variant:state.variant,page,lang:state.lang,...extra})}`;}
function link(page,label,cls=''){return `<a class="${cls}" ${cls==='active'?'aria-current="page"':''} href="${url(page)}" data-page="${page}">${label}</a>`;}
function icon(p,size=''){return p.kind==='mac'?`<img class="app-icon ${size}" src="assets/${p.id}-icon.png" alt="">`:`<span class="type-mark ${size}" aria-hidden="true">${p.kind==='mcp'?'MCP':'SB'}</span>`;}
function repo(p){return `https://github.com/rmarinsky/${p.repo}`;}
function ext(href,label,cls='text-link'){return `<a class="${cls}" href="${href}" target="_blank" rel="noreferrer">${label}<span aria-hidden="true"> ↗</span></a>`;}
function readState(){const params=new URLSearchParams(location.search);const page=params.get('page')||'home';state={variant:['A','B','C'].includes(params.get('variant'))?params.get('variant'):'A',lang:params.get('lang')==='en'?'en':'uk',page:(Object.hasOwn(pageNames.uk,page)||byId(page))?page:'404'};}
function header(){return `<header class="site-header"><a class="wordmark" href="${url('home')}" data-page="home">Roman<br><span>Marinsky</span><i aria-hidden="true">.</i></a><nav aria-label="${t('Основна навігація','Main navigation')}">${link('home',t('Інструменти','Tools'),state.page==='home'?'active':'')}${link('discover',t('За задачею','By task'),state.page==='discover'?'active':'')}${link('updates',t('Оновлення','Updates'),state.page.startsWith('update')?'active':'')}${link('about',t('Про мене','About'),state.page==='about'?'active':'')}</nav><a class="language" href="${url(state.page,{lang:state.lang==='uk'?'en':'uk'})}" data-language="${state.lang==='uk'?'en':'uk'}" aria-label="${t('Switch to English','Перемкнути українською')}">${state.lang==='uk'?'EN':'UA'}</a></header>`;}
function footer(){return `<footer class="site-footer"><div><strong>Roman Marinsky</strong><p>${t('Зроблено у Львові, Україна.','Made in Lviv, Ukraine.')}</p></div><div>${ext('https://github.com/rmarinsky','GitHub')}${ext('mailto:roman@rmarinsky.com.ua',t('Написати','Get in touch'))}${link('legal',t('Дані та умови','Data & terms'))}</div><small>${t('Прототип · факти за каталогом від 28.09.2026','Prototype · facts from the 28 Sep 2026 catalogue')}</small></footer>`;}
function demo(p,{compact=false}={}){
 if(p.kind==='mac')return `<figure class="demo-player ${compact?'compact':''}"><div class="demo-top"><span>${icon(p)}${name(p)}</span><small>${t('12 секунд · без звуку','12 seconds · silent')}</small></div><video controls muted playsinline loop preload="metadata" poster="media/${p.id}-poster.jpg" aria-label="${esc(txt(p.demo))}"><source src="media/${p.id}.mp4" type="video/mp4"><track default kind="captions" srclang="uk" label="Українська" src="media/${p.id}.vtt"></video><figcaption><span>${txt(p.demo)}</span><span>${t('Сценарне відтворення','Illustrated workflow')}</span></figcaption></figure>`;
 if(p.kind==='browser')return `<figure class="context-demo"><div class="demo-top"><span>SideBarny</span><small>${t('Схема сценарію','Workflow sketch')}</small></div><div class="context-columns"><div><span class="micro">${t('СТОРІНКА','PAGE')}</span><h3>${t('План наступного релізу','Next release plan')}</h3><p>${t('Перевірити виправлення, оновити документацію, підготувати приклади.','Check fixes, update documentation, prepare examples.')}</p><mark>${t('Спершу перевіримо основний сценарій на чистому профілі.','First, check the main flow in a clean profile.')}</mark><button class="small-button" data-capture>${t('Передати фрагмент →','Pass excerpt →')}</button></div><div><span class="micro">${t('ПОЛЕ AI-ЧАТУ','AI CHAT INPUT')}</span><div id="capture-result" role="status">${t('Тут з’явиться вибраний фрагмент.','The selected excerpt will appear here.')}</div><small>${t('Вставлення не надсилає повідомлення.','Inserting does not send the message.')}</small></div></div><figcaption>${t('Інтерактивна схема. Не справжній AI-чат.','Interactive sketch. Not a live AI chat.')}</figcaption></figure>`;
 const dns=p.id==='ukraine-com-ua-mcp';
 return `<figure class="terminal-demo"><div class="terminal-head"><span>MCP / ${dns?'adm.tools':'WayForPay'}</span><span>${t('приклад відповіді','example response')}</span></div><p class="terminal-prompt">${dns?t('Покажи DNS-записи example.com.','Show DNS records for example.com.'):t('Знайди оплату за замовленням DEMO-1042.','Find the payment for order DEMO-1042.')}</p><pre><code>${dns?'list_dns_records({domain_id: "demo"})\n\n@    A      192.0.2.10\nwww  CNAME  example.com.':'wfp_search_transactions({\n  dateFrom: "2026-09-01",\n  dateTo: "2026-09-07",\n  orderReference_contains: "DEMO-1042"\n})\n\nDEMO-1042  ·  Approved  ·  420 UAH'}</code></pre><p class="terminal-result">${dns?t('Спочатку читаємо. Перед зміною - backup.','Read first. Back up before changing.'):t('Є конкретний платіж і його статус.','A specific payment and its status.')}</p><figcaption>${t('Демонстраційні дані. Запит не виконується.','Sample data. No request is executed.')}</figcaption></figure>`;
}
function productTabs(){return `<div class="demo-tabs" role="group" aria-label="${t('Обрати демонстрацію','Choose a demo')}">${products.filter(p=>p.kind==='mac').map(p=>`<button data-select="${p.id}" aria-pressed="${selected===p.id}">${icon(p)}${name(p)}</button>`).join('')}</div>`;}
function home(){const p=byId(selected);const small=products.filter(p=>p.kind!=='mac');
 const intro=`<span class="eyebrow">${t('Роман Маринський · Львів','Roman Marinsky · Lviv')}</span><h1>${t('Роблю програми.<br>І користуюся<br>ними щодня.','I make tools.<br>And use them<br>every day.')}</h1><p class="lead">${t('Пишу, перемикаюся між проєктами, працюю з записами. Ось кілька речей, які прибирають зайві дії з цього дня.','Writing, switching projects, working with recordings. These tools remove a few repeated steps from that day.')}</p>${link('about',t('Трохи про мене ↗','A little about me ↗'),'underlink')}`;
 let hero;
 if(state.variant==='A')hero=`<section class="home-hero editorial"><div class="intro">${intro}</div><div class="hero-evidence">${productTabs()}${demo(p)}<p class="under-demo">${txt(p.short)} ${link(p.id,t('Докладніше →','Explore →'))}</p></div></section>`;
 else if(state.variant==='B')hero=`<section class="index-hero"><div class="index-heading"><span class="eyebrow">${t('Роман Маринський / інструменти','Roman Marinsky / tools')}</span><h1>${t('Що потрібно<br>зробити?','What do you<br>need to do?')}</h1><p>${t('Обери задачу. Подивись результат.','Choose a task. See the result.')}</p></div><div class="tool-index">${products.filter(p=>p.kind==='mac').map((x,i)=>`<button data-select="${x.id}" class="index-row" aria-pressed="${x.id===selected}"><span>0${i+1}</span>${icon(x)}<span><strong>${name(x)}</strong><small>${txt(x.short)}</small></span><b>↗</b></button>`).join('')}</div><div class="index-preview">${demo(p)}${link(p.id,t('Відкрити сторінку '+name(p),'Open '+name(p)),'button')}</div></section>`;
 else hero=`<section class="cinema-hero"><div class="cinema-top"><span class="eyebrow">${t('Менше пояснень. Одна дія.','Less explanation. One action.')}</span><h1>${selected==='papuga'?t('Не переписуй.','Don’t retype.'):selected==='appcat'?t('Відкрий там, де треба.','Open it where it belongs.'):t('Скажи. І продовжуй.','Say it. Keep going.')}</h1></div><div class="cinema-stage">${demo(p)}<aside>${productTabs()}<p>${txt(p.intro)}</p>${link(p.id,t('До сторінки '+name(p)+' →','Explore '+name(p)+' →'),'button')}<p class="small-muted">${t('Інструменти Романа Маринського.<br>Львів, Україна.','Tools by Roman Marinsky.<br>Lviv, Ukraine.')}</p></aside></div></section>`;
 return `${hero}<section class="product-shelf"><div class="section-heading"><span class="eyebrow">${t('Для Mac','For Mac')}</span><h2>${t('Три різні задачі.<br>Три окремі інструменти.','Three different jobs.<br>Three separate tools.')}</h2></div>${products.filter(x=>x.kind==='mac').map((x,i)=>`<article class="shelf-row"><span class="ordinal">0${i+1}</span>${icon(x,'large')}<div><h3>${link(x.id,name(x))}</h3><p>${txt(x.short)}</p></div><div class="shelf-detail"><span>macOS 14+ · v${x.version}</span>${link(x.id,t('Подивитися в дії →','See it in action →'))}</div></article>`).join('')}</section><section class="other-tools"><div><span class="eyebrow">${t('Браузер та інтеграції','Browser & integrations')}</span><h2>${t('Ще кілька<br>корисних з’єднань.','A few more<br>useful connections.')}</h2><p>${t('Окремі інструменти для контексту сторінки, платежів і DNS.','Separate tools for page context, payments and DNS.')}</p></div><div>${small.map(x=>`<article><h3>${link(x.id,name(x)+' ↗')}</h3><p>${txt(x.short)}</p><span class="small-muted">${x.kind==='browser'?'Chrome / GitHub':'MCP / npm'}</span></article>`).join('')}</div></section><section class="author-note"><span class="eyebrow">${t('Від автора','From the maker')}</span><p>${t('Ці інструменти роблю й підтримую я. Код, вимоги та посилання на релізи зібрав поруч із кожним.','I make and maintain these tools. Each page includes the code, requirements and release links.')}</p>${link('about',t('Роман Маринський →','Roman Marinsky →'))}</section>`;
}
function actions(p){return `<div class="product-actions">${p.kind==='mac'?ext(repo(p)+`/releases/tag/v${p.version}`,t('Завантажити для Mac','Download for Mac'),'button'):p.kind==='browser'?ext(repo(p)+'#readme',t('Встановлення з GitHub','Install from GitHub'),'button'):`<button class="button" data-install="${p.id}">${t('Налаштувати MCP','Set up MCP')}</button>`}${ext(repo(p),t('Код і документація','Source & docs'))}</div><p class="release-line">${p.kind==='mac'?'macOS 14+ · ':''}v${p.version} · ${p.date} <span>${t('за каталогом 28.09.2026','catalogued 28 Sep 2026')}</span></p>`;}
function productPage(p){const headline=`<div class="product-title">${icon(p,'hero-icon')}<span class="eyebrow">${name(p)} / ${p.kind==='mac'?'macOS':p.kind==='browser'?'Chrome':'MCP'}</span><h1>${txt(p.title).split('\n').join('<br>')}</h1><p class="lead">${txt(p.intro)}</p>${actions(p)}</div>`;
 let top=state.variant==='A'?`<section class="product-hero">${headline}<div class="product-evidence">${demo(p)}<ol class="steps">${txt(p.examples).map((s,i)=>`<li><span>0${i+1}</span>${s}</li>`).join('')}</ol></div></section>`:state.variant==='B'?`<section class="product-index"><aside class="product-contents">${icon(p,'hero-icon')}<strong>${name(p)}</strong><a href="#scenario">${t('Демонстрація','Demonstration')}</a><a href="#features">${t('Можливості','Capabilities')}</a><a href="#requirements">${t('Перед встановленням','Before installing')}</a><a href="#data">${t('Дані','Data')}</a></aside><div><div id="scenario">${headline}</div>${demo(p)}</div></section>`:`<section class="product-cinema"><div class="cinema-product-heading"><span class="eyebrow">${name(p)} · ${t('один сценарій','one workflow')}</span><h1>${txt(p.title).replace('\n',' ')}</h1></div>${demo(p)}<div class="cinema-product-intro"><p class="lead">${txt(p.intro)}</p><div>${actions(p)}</div></div></section>`;
 return `${link('home',t('← Усі інструменти','← All tools'),'back-link')}${top}<section class="feature-section" id="features"><div class="section-heading"><span class="eyebrow">${t('Далі можна','You can also')}</span><h2>${t('Що ще всередині.','What else is inside.')}</h2></div><div class="feature-list">${txt(p.jobs).map((j,i)=>`<article><span class="ordinal">0${i+1}</span><h3>${j[0]}</h3><p>${j[1]}</p></article>`).join('')}</div></section><section class="requirements" id="requirements"><h2>${t('Перед встановленням','Before installing')}</h2><p>${txt(p.boundary)}</p></section><section class="data-section" id="data"><span class="eyebrow">${t('Про дані, конкретно','About your data')}</span><h2>${t('Що залишається локально.<br>Що використовує мережу.','What stays local.<br>What uses the network.')}</h2><p>${txt(p.privacy)}</p></section><section class="one-question"><h3>${txt(p.question)}</h3><p>${txt(p.answer)}</p></section><div class="closing-action"><div><h2>${t('Спробуй на своїй задачі.','Try it with your own work.')}</h2><p>${t('Один короткий сценарій скаже більше за список обіцянок.','One short workflow says more than a list of promises.')}</p></div>${actions(p)}</div>`;
}
function sectionTitle(kicker,title,lead=''){return `<header class="page-heading"><span class="eyebrow">${kicker}</span><h1>${title}</h1>${lead?`<p class="lead">${lead}</p>`:''}</header>`;}
function discovery(){return `${sectionTitle(t('Почни із задачі','Start with a task'),t('Що заважає<br>працювати?','What’s getting<br>in your way?'),t('Шість інструментів. Без тесту з двадцяти запитань.','Six tools. No twenty-question quiz.'))}<div class="finder"><label for="search">${t('Пошук за задачею або назвою','Search by task or name')}</label><input type="search" id="search" placeholder="${t('Наприклад: розкладка, аудіо, DNS','For example: layout, audio, DNS')}" value="${esc(query)}"><div class="filter-row">${[['all',t('Усе','All')],['mac','Mac'],['browser',t('Браузер','Browser')],['mcp','MCP']].map(([k,l])=>`<button data-filter="${k}" aria-pressed="${filter===k}">${l}</button>`).join('')}</div><p class="search-count" aria-live="polite"></p><div id="search-results"></div></div>`;}
function results(){const q=query.trim().toLocaleLowerCase();const list=products.filter(p=>(filter==='all'||p.kind===filter)&&[...Object.values(p.name),...Object.values(p.short),...Object.values(p.jobs).flat(2)].join(' ').toLocaleLowerCase().includes(q));$('.search-count').textContent=t(`Знайдено: ${list.length}`,`${list.length} results`);$('#search-results').innerHTML=list.length?list.map(p=>`<article class="result-row">${icon(p,'large')}<div><h2>${link(p.id,name(p))}</h2><p>${txt(p.short)}</p><small>${txt(p.boundary)}</small></div>${link(p.id,t('Переглянути →','Explore →'),'result-link')}</article>`).join(''):`<div class="empty"><h2>${t('Збігів немає.','No matches.')}</h2><p>${t('Спробуй коротшу назву або поверни весь каталог.','Try a shorter phrase or return to the full catalogue.')}</p><button data-reset class="button">${t('Показати все','Show all')}</button></div>`;}
function updates(){return `${sectionTitle(t('Робочий журнал','Work log'),t('Що змінилося.','What changed.'),t('Дата, зміна й місце, де її можна перевірити.','A date, a change and somewhere to verify it.'))}<div class="journal-layout"><aside><span class="micro">${t('У ЦЬОМУ ПРОТОТИПІ','IN THIS PROTOTYPE')}</span><p>${t('Показаний наявний запис із сайту. Нових релізних історій тут не вигадано.','This uses the site’s existing update. No release stories have been invented.')}</p>${ext('https://github.com/rmarinsky',t('Репозиторії автора','Maker’s repositories'))}</aside><article class="journal-row"><time datetime="2026-07-06">06.07.2026</time><span class="eyebrow">${t('Сайт / інфраструктура','Website / infrastructure')}</span><h2>${link('update',t('Сайт переїхав на GitHub Pages. HTTPS працює.','The site moved to GitHub Pages. HTTPS works.'))}</h2><p>${t('Прибрані старі DNS-записи, виправлений сертифікат і налаштований канал оновлень.','Old DNS records removed, certificate fixed and an update channel in place.')}</p>${link('update',t('Що саме змінилося →','Read the change →'))}</article></div>`;}
function update(){return `${link('updates',t('← Усі оновлення','← All updates'),'back-link')}<article class="reading-layout"><aside><time datetime="2026-07-06">06.07.2026</time><p>${t('Сайт<br>Інфраструктура','Website<br>Infrastructure')}</p>${ext('https://github.com/rmarinsky/rmarinsky.com.ua/actions/runs/28797495048',t('Доказ: deploy','Evidence: deploy'))}</aside><div>${sectionTitle(t('Нотатка про зміну','Change note'),t('Один сайт.<br>Правильний сертифікат.','One site.<br>The right certificate.'))}<p class="article-lead">${t('Посилання на сайт було, але HTTPS сварився. Частина адрес усе ще вела на старий хостинг.','The site had an address, but HTTPS failed. Some addresses still pointed to the old host.')}</p><h2>${t('Що змінив','What changed')}</h2><p>${t('Оновив A та AAAA записи для GitHub Pages, прибрав wildcard, додав verification TXT і дочекався нового сертифіката. Потім повторив deploy.','Updated the A and AAAA records for GitHub Pages, removed the wildcard, added verification TXT and waited for the new certificate. Then ran deployment again.')}</p><h2>${t('Що це дало','The result')}</h2><p>${t('За опублікованою нотаткою від 6 липня, HTTP перенаправлявся на HTTPS, а сертифікат покривав основний домен і www. Це історичний запис, не нова перевірка доступності.','The published 6 July note reports HTTP redirecting to HTTPS and a certificate covering the main domain and www. This is a historical entry, not a new uptime check.')}</p><div class="source-note">${t('Скорочена подача наявної нотатки. Факти з src/content/updates.ts.','A shorter presentation of the existing entry in src/content/updates.ts.')}</div></div></article>`;}
function about(){return `<div class="about-layout"><div>${sectionTitle(t('Роман Маринський / Львів, Україна','Roman Marinsky / Lviv, Ukraine'),t('Пишу код.<br>Перевіряю, як<br>він працює.','I write software.<br>Then check how<br>it works.'))}<p class="article-lead">${t('Я працюю з QA та автоматизацією тестування, створюю macOS-застосунки й організовую спільноти.','I work in QA and test automation, build macOS applications and organise communities.')}</p><p>${t('Тут зібрані мої інструменти: для тексту, посилань, записів, браузера та кількох щоденних інтеграцій. Кожен має окрему задачу й свої обмеження.','This is a collection of my tools for text, links, recordings, the browser and a few everyday integrations. Each has its own job and limits.')}</p><div class="about-contact">${ext('mailto:roman@rmarinsky.com.ua',t('Написати Роману','Email Roman'),'button')}${ext('https://www.linkedin.com/in/rmarinsky/','LinkedIn')}${ext('https://github.com/rmarinsky','GitHub')}</div></div><aside class="author-index"><span class="eyebrow">${t('Над чим працюю','What I work on')}</span>${products.filter(p=>p.kind==='mac').map(p=>`<article>${icon(p)}<div>${link(p.id,name(p))}<p>${txt(p.short)}</p></div></article>`).join('')}<div class="community"><span class="eyebrow">${t('Люди поруч','Community')}</span>${ext('https://t.me/qa_club_lviv','QA Club Lviv')}<p>${t('Організатор спільноти.','Community organiser.')}</p></div></aside></div><section class="author-note"><span class="eyebrow">${t('Як хочу про це говорити','How I want to explain the work')}</span><p>${t('Показати, де інструмент корисний. Не приховати, де він має межі. Дати можливість перевірити самому.','Show where a tool helps. Explain where its limits are. Give you a way to check it yourself.')}</p></section>`;}
function legal(){return `${sectionTitle(t('Прозорість','Transparency'),t('Дані й умови.<br>Окремо для кожного.','Data and terms.<br>Tool by tool.'),t('Прототип структури сторінки. Це не нова юридична політика.','A prototype of this page’s structure. Not a new legal policy.'))}<div class="legal-layout"><aside><a href="#website">${t('Цей сайт','This website')}</a><a href="#apps-data">${t('Застосунки','Applications')}</a><a href="#terms">${t('Умови','Terms')}</a><a href="#contact">${t('Контакт','Contact')}</a></aside><div><section id="website"><h2>${t('Цей сайт','This website')}</h2><p>${t('У цьому локальному прототипі немає аналітики, форм збору даних або збереження введених запитів. Вибір сторінки, мови й напряму записаний лише в URL.','This local prototype has no analytics, data-collection forms or stored search queries. Page, language and design choices live in the URL.')}</p></section><section id="apps-data"><h2>${t('Що роблять застосунки','What the applications do')}</h2>${products.map(p=>`<details><summary>${name(p)}</summary><p>${txt(p.privacy)}</p>${link(p.id,t('До сторінки продукту →','Product page →'))}</details>`).join('')}</section><section id="terms"><h2>${t('Умови й ліцензії','Terms and licences')}</h2><p>${t('Ліцензії та вимоги залежать від продукту. Публічний репозиторій сам по собі не встановлює ліцензію. Перед публікацією цієї структури потрібно узгодити остаточні тексти для кожного продукту.','Licences and requirements vary by product. A public repository alone does not establish a licence. Final wording for each product needs review before this structure is published.')}</p></section><section id="contact"><h2>${t('Питання про дані','Questions about data')}</h2>${ext('mailto:roman@rmarinsky.com.ua','roman@rmarinsky.com.ua')}</section></div></div>`;}
function notFound(){return `<section class="not-found"><span class="eyebrow">404 / ${t('Такої сторінки немає','Page not found')}</span><h1>${t('Посилання загубилося.<br>Інструменти - на місці.','The link got lost.<br>The tools are still here.')}</h1><p>${t('Повернися до каталогу або знайди потрібний продукт за задачею.','Return to the catalogue or find the right tool by task.')}</p><div class="product-actions">${link('home',t('Усі інструменти','All tools'),'button')}${link('discover',t('Знайти за задачею →','Find by task →'))}</div></section>`;}
function tools(){return `<aside class="prototype-bar" aria-label="${t('Керування прототипом','Prototype controls')}"><span class="prototype-label">${t('Прототип','Prototype')}</span><button class="cycle" data-cycle="-1" aria-label="${t('Попередній напрям','Previous direction')}">←</button><div class="variants">${Object.entries(variants).map(([k,v])=>`<button data-variant="${k}" aria-pressed="${state.variant===k}" title="${v[state.lang][1]}"><b>${k}</b><span>${v[state.lang][0]}</span></button>`).join('')}</div><button class="cycle" data-cycle="1" aria-label="${t('Наступний напрям','Next direction')}">→</button><label class="page-picker"><span class="sr-only">${t('Сторінка','Page')}</span><select id="page-select">${Object.entries(pageNames[state.lang]).sort(([a],[b])=>(a==='404')-(b==='404')).map(([k,v])=>`<option value="${k}" ${k===state.page?'selected':''}>${v}</option>`).join('')}${products.map(p=>`<option value="${p.id}" ${p.id===state.page?'selected':''}>${name(p)}</option>`).join('')}</select></label><button data-review class="review-button">${t('Що змінили?','What changed?')}</button></aside>`;}
function render(scroll=true){readState();document.documentElement.lang=state.lang;document.body.dataset.variant=state.variant;document.body.dataset.page=state.page;document.title=`${byId(state.page)?name(byId(state.page)):pageNames[state.lang][state.page]} · ${variants[state.variant][state.lang][0]} · Prototype`;
 const body=byId(state.page)?productPage(byId(state.page)):({home,discover:discovery,updates,update,about,legal,'404':notFound}[state.page])();
 $('#app').innerHTML=`<div class="shell">${header()}<main id="main" tabindex="-1">${body}</main>${footer()}</div>`;$('#prototype-tools').innerHTML=tools();if(state.page==='discover')results();if(scroll)window.scrollTo({top:0,behavior:'instant'});}
function navigate(page,extra={},scroll=true){history.pushState({},'',url(page,extra));render(scroll);}
function review(){const notes=state.lang==='uk'?improvements:improvementsEn;const [before,after]=notes[state.page]||notes.home;const dialog=$('#review-dialog');dialog.innerHTML=`<button class="dialog-close" data-close aria-label="${t('Закрити','Close')}">×</button><span class="eyebrow">${t('Дизайн-розбір / ця сторінка','Design review / this page')}</span><h2 id="dialog-title">${variants[state.variant][state.lang][0]}</h2><p>${variants[state.variant][state.lang][1]}</p><div class="review-columns"><section><h3>${t('Було','Before')}</h3><p>${before}</p></section><section><h3>${t('Пропозиція','Proposal')}</h3><p>${after}</p></section></div>${state.page==='home'?'<img class="before-shot" src="assets/before-home.png" alt="Головна сторінка до змін, 25.09.2026">':''}<h3>${t('Що можна перевірити тут','What you can try')}</h3><p>${t('Перемикай A/B/C, усі сторінки й мову. Відтворюй відео, користуйся пошуком, фільтрами та налаштуванням MCP. Стрілки ← → змінюють напрям.','Switch A/B/C, pages and language. Play videos, search, filter and open MCP setup. Left/right arrows change direction.')}</p><p class="source-note">${t('Демо - сценарні відтворення з умовними даними. Перед публікацією замінимо їх на перевірені записи апок.','Demos are illustrated workflows with sample data. Replace them with verified app recordings before publishing.')}</p><a href="PAGE-PLAN.md" target="_blank">${t('План змін для всіх сторінок ↗','Page-by-page plan (Ukrainian) ↗')}</a>`;dialog.showModal();}
function install(id){const p=byId(id);const dns=id==='ukraine-com-ua-mcp';const cfg={mcpServers:{[dns?'adm-tools':'wayforpay']:{command:'npx',args:['-y',`@rmarinsky/${id}@${p.version}`],env:dns?{ADM_TOOLS_TOKEN:'YOUR_TOKEN',ADM_TOOLS_ENABLE_WRITE_TOOLS:'false'}:{WFP_MERCHANTS_JSON:'[{"alias":"demo","merchantAccount":"YOUR_ACCOUNT","secretKey":"YOUR_SECRET"}]',WFP_ENABLE_WRITE_TOOLS:'false'}}}};const dialog=$('#review-dialog');dialog.innerHTML=`<button class="dialog-close" data-close aria-label="${t('Закрити','Close')}">×</button><span class="eyebrow">${name(p)}</span><h2 id="dialog-title">${t('Почни з читання.','Start with read access.')}</h2><p>${t('Цей приклад вимикає write tools. Замінити позначки потрібно у власній локальній конфігурації - не вводь секрети на сайті.','This example disables write tools. Replace placeholders in your local configuration. Do not enter secrets on this site.')}</p><p class="source-note">${dns?t('Потрібні Node 20+ і MCP-клієнт.','Requires Node 20+ and an MCP client.'):t('Потрібні Node 20+, Bun 1.1+ і MCP-клієнт. Релізний entrypoint використовує Bun.','Requires Node 20+, Bun 1.1+ and an MCP client. The release entrypoint uses Bun.')}</p><pre class="config-code"><code>${esc(JSON.stringify(cfg,null,2))}</code></pre><button data-copy-config class="button">${t('Скопіювати приклад','Copy example')}</button><p class="copy-status" role="status"></p>${ext(repo(p)+'#readme',t('Повна документація','Full documentation'))}`;dialog.showModal();}
document.addEventListener('click',async e=>{const target=e.target.closest('a,button');if(!target)return;
 if(target.dataset.page){if(e.ctrlKey||e.metaKey)return;e.preventDefault();navigate(target.dataset.page);}
 else if(target.dataset.variant){navigate(state.page,{variant:target.dataset.variant},false);}
 else if(target.dataset.cycle){const keys=['A','B','C'];navigate(state.page,{variant:keys[(keys.indexOf(state.variant)+Number(target.dataset.cycle)+3)%3]},false);}
 else if(target.dataset.language){e.preventDefault();navigate(state.page,{lang:target.dataset.language},false);}
 else if(target.dataset.select){selected=target.dataset.select;render(false);}
 else if(target.hasAttribute('data-review'))review();
 else if(target.hasAttribute('data-close'))$('#review-dialog').close();
 else if(target.dataset.filter){filter=target.dataset.filter;document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.filter===filter)));results();}
 else if(target.hasAttribute('data-reset')){query='';filter='all';render(false);$('#search').focus();}
 else if(target.hasAttribute('data-capture')){$('#capture-result').textContent=t('Спершу перевіримо основний сценарій на чистому профілі.','First, check the main flow in a clean profile.');target.textContent=t('Фрагмент вставлено','Excerpt inserted');target.disabled=true;}
 else if(target.dataset.install)install(target.dataset.install);
 else if(target.hasAttribute('data-copy-config')){try{await navigator.clipboard.writeText($('.config-code').textContent);$('.copy-status').textContent=t('Скопійовано. Секрети залишаються у твоїй конфігурації.','Copied. Keep secrets in your local configuration.');}catch{$('.copy-status').textContent=t('Копіювання недоступне. Виділи приклад і скопіюй вручну.','Clipboard unavailable. Select and copy the example manually.');}}
});
document.addEventListener('input',e=>{if(e.target.id==='search'){query=e.target.value;results();}});
document.addEventListener('change',e=>{if(e.target.id==='page-select')navigate(e.target.value);});
document.addEventListener('keydown',e=>{if($('#review-dialog').open||e.target.closest('input,textarea,select,button,video,[contenteditable]')||!['ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();const keys=['A','B','C'];navigate(state.page,{variant:keys[(keys.indexOf(state.variant)+(e.key==='ArrowRight'?1:2))%3]},false);});
window.addEventListener('popstate',()=>render());
render();
