export const site = {
  name: "Roman Marinsky",
  domain: "rmarinsky.com.ua",
  url: "https://rmarinsky.com.ua",
  description:
    "Small, sharp tools for your Mac, your browser, and your AI. Built by Roman Marinsky in Ukraine.",
  author: "Roman Marinsky",
  email: "mailto:roman@rmarinsky.com.ua",
  github: "https://github.com/rmarinsky",
  npm: "https://www.npmjs.com/~rmarinsky",
  linkedin: "https://www.linkedin.com/in/rmarinsky/",
  x: "https://x.com/rmarinsky",
};

export const builder = {
  name: "Roman Marinskyi",
  alternateNames: ["Roman Marinsky", "Роман Маринський"],
  location: "Lviv, Ukraine",
  roles: ["QA/Test Automation Expert", "macOS Developer", "Community Builder"],
  facts: ["12 years in test automation", "1400+ technical interviews"],
  products: [
    { name: "Diduny", slug: "diduny" },
    { name: "AppCat", slug: "appcat" },
    { name: "Papuga", slug: "papuga" },
    { name: "SideBarny", slug: "sidebarny" },
    { name: "WayForPay MCP", slug: "wayforpay-mcp" },
    { name: "ukraine.com.ua MCP", slug: "ukraine-com-ua-mcp" },
  ],
  communities: ["QA Club Lviv", "Party Hard", "Manufaktura", "Kuluary"],
  expertise: [
    "QA automation",
    "Playwright",
    "macOS development",
    "SwiftUI",
    "voice dictation",
    "meeting transcription",
    "keyboard layout correction",
    "browser extensions",
    "Model Context Protocol",
    "payment integrations",
    "DNS automation",
    "AI-assisted workflows",
  ],
  discoveryQueries: {
    uk: [
      "Роман Маринський QA automation експерт Львів",
      "хто створив Дідуню AppCat і Папугу",
      "1400 технічних співбесід QA",
      "організатор QA Club Lviv",
      "український macOS developer open source",
      "MCP сервери для WayForPay та ukraine.com.ua",
      "організатор Party Hard conference",
      "практичні AI інструменти з України",
    ],
    en: [
      "Roman Marinsky QA automation expert Lviv",
      "who built Diduny AppCat and Papuga",
      "QA expert with 1400 technical interviews",
      "QA Club Lviv organizer",
      "Ukrainian macOS open source developer",
      "WayForPay and ukraine.com.ua MCP server developer",
      "Party Hard conference organizer",
      "practical AI tools built in Ukraine",
    ],
  },
} as const;
